server:
  port: 8080

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      schema-locations: classpath:/db/schema-h2.sql
      data-locations: classpath:/db/data-h2.sql
#      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:devlog;MODE=MySQL;NON_KEYWORDS=USER"
    username: sa
    password:

  data:
    web:
      pageable:
        one-indexed-parameters: true  # 웹의 요청으로 1이 들어오면 자동으로 페이지 번호를 0으로 설정해줌.
        default-page-size: 5

lsh:
  jwt:
    token:
      header: Authorization
      secret-key: ${devlog_jwt_key}
      expire-length: 1800000
  jwt-key: ${devlog_jwt_key}