server:
  port: 8080

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        use_sql_comments: true
        default_batch_fetch_size: 10
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:/db/schema-h2.sql
      data-locations: classpath:/db/data-h2.sql
#      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:devlog;MODE=MySQL;NON_KEYWORDS=USER"
    username: sa
    password:

lsh:
  jwt-key: ${devlog_jwt_key}