### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "lsh1234@gmail.com",
  "password": "1234",
  "name": "LEE_SH"
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "lsh1234@gmail.com",
  "password": "1234",
  "remember": 1
}

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMDI2ODY1fQ.Fqk5P1ppRVqnpYGIbmUY1dRfDkS2VNj1a84xOis8vKM
#Cookie: SESSION=8505e746-403c-4a16-ac09-7ea1f8e7225e

### 메인 페이지 요청
GET http://localhost:8080

### 사용자 페이지
GET http://localhost:8080/user

### 관리자 페이지
GET http://localhost:8080/admin