### 댓글 작성

POST http://localhost:8080/posts/1/comments
Content-Type: application/json

{
  "author": "lsh",
  "password": "123456",
  "content": "content123456"
}

### 댓글 삭제

POST http://localhost:8080/comments/1/delete
Content-Type: application/json

{
  "password": "123456"
}