### 게시글 작성

POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsc2gxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTY5MjQ1NTUzOSwiZXhwIjoxNjkyNDU3MzM5fQ.hoqVoXfVUMaQ6bPA7B0Jpl3GF-SeuYHICzDMgoZ_E3A

{
  "title": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been",
  "content": "본문 11"
}

### 게시글 수정

PATCH http://localhost:8080/posts/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsc2gxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTY5MjQyMDEwNywiZXhwIjoxNjkyNDIxOTA3fQ.50Sr6vKWqdB2-NfBtTf2CSlXQkTfIT8AiPICFZQ306w

{
  "title": "수정된 제목 11",
  "content": "본문 11"
}

### 게시글 삭제

DELETE http://localhost:8080/posts/11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsc2gxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTY5MjQyMDEwNywiZXhwIjoxNjkyNDIxOTA3fQ.50Sr6vKWqdB2-NfBtTf2CSlXQkTfIT8AiPICFZQ306w
